name: super_sliver_list
description: "Drop-in replacement for SliverList and ListView that can handle large lists with variable extents and jump/animate to specific items."
version: 0.4.1
homepage: https://github.com/superlistapp/super_sliver_list

environment:
  sdk: ">=3.7.2 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.19.1
  logging: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^2.8.0
  test: ^1.25.15
  sliver_tools: ^0.2.12